name: (🚀) => Publish

on:
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: (🔺) Checkout
              uses: actions/checkout@v4

            - name: (🔺) Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'

            - name: (🔺) Installing Dependencies...
              run: yarn install

            - name: (🔺) Testing...
              run: yarn test

            - name: (🔺) Building...
              run: |
                  yarn build

            - name: (🔺) Publishing... (NPM)
              run: |
                  yarn publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
