name: (🚀) Publish

on:
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: (🔺) Checkout
              uses: actions/checkout@v4

            - name: (🔺) Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'

            - name: (🔺) Installing Dependencies...
              run: pnpm install .

            - name: (🔺) Testing...
              run: pnpm run test

            - name: (🔺) Building...
              run: |
                  pnpm run build

            - name: (🔺) Publishing...
              run: |
                  pnpm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
